document.querySelectorAll(".nav-2-items").forEach((element)=>{element.querySelectorAll("a").forEach((e)=>{if(e.getAttribute("href")===window.location.href){if(e.parentElement.parentElement.classList.value==="dropdown-list"){e.classList.add("active-dropdown");e.parentElement.parentElement.parentElement.querySelector("a").classList.add("active")}else{e.classList.add("active")}}})});window.addEventListener("scroll",()=>{if(window.scrollY>300){document.getElementById("moveTopBtn").style.bottom="11px"}else{document.getElementById("moveTopBtn").style.bottom="-100px"}});window.addEventListener("DOMContentLoaded",()=>{document.querySelector(".loader").style.opacity="0";setTimeout(()=>{document.querySelector(".loader").style.display="none";document.querySelector("body").style.overflowY="visible"},500)});if(document.cookie!=""){document.getElementById("cartBtn").style.left="11px"}
function servicesSlides(n,k){let headings=["Men's Tailoring","Wedding Dress Alterations","Clothing Design And Repairs","Ladies Tailoring",];let paragraphs=["Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cupiditate atque, nostrum blanditiis incidunt laborum, dolor nobis ipsum dolorum fugit soluta, ipsam accusantium porro voluptatum delectus explicabo similique iste voluptatem est officiis sit! Non soluta sunt eligendi dolorem dolore ducimus porro, excepturi voluptas, esse consequuntur inventore blanditiis culpa nisi dolor qui.","Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cupiditate atque, nostrum blanditiis incidunt laborum, dolor nobis ipsum dolorum fugit soluta, ipsam accusantium porro voluptatum delectus explicabo similique iste voluptatem est officiis sit! Non soluta sunt eligendi dolorem dolore ducimus porro, excepturi voluptas, esse consequuntur inventore blanditiis culpa nisi dolor qui.","Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cupiditate atque, nostrum blanditiis incidunt laborum, dolor nobis ipsum dolorum fugit soluta, ipsam accusantium porro voluptatum delectus explicabo similique iste voluptatem est officiis sit! Non soluta sunt eligendi dolorem dolore ducimus porro, excepturi voluptas, esse consequuntur inventore blanditiis culpa nisi dolor qui.","Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cupiditate atque, nostrum blanditiis incidunt laborum, dolor nobis ipsum dolorum fugit soluta, ipsam accusantium porro voluptatum delectus explicabo similique iste voluptatem est officiis sit! Non soluta sunt eligendi dolorem dolore ducimus porro, excepturi voluptas, esse consequuntur inventore blanditiis culpa nisi dolor qui.",];let h3=document.getElementsByClassName("services-container")[0].querySelector("h3");let p=document.getElementsByClassName("services-container")[0].querySelector("p");h3.style.transition="all 0.25s ease-in-out";p.style.transition="all 0.25s ease-in-out";h3.style.right="-120%";p.style.left="-120%";setTimeout(()=>{h3.style.transition="";p.style.transition="";h3.style.right="120%";p.style.left="120%"},250);setTimeout(()=>{h3.style.transition="all 0.4s ease-in-out";p.style.transition="all 0.4s ease-in-out";h3.innerText=headings[k-1];p.innerText=paragraphs[k-1];h3.style.right="0";p.style.left="0"},300);for(let k=0;k<document.getElementsByClassName("dot").length;k++){document.getElementsByClassName("dot")[k].style.backgroundColor="transparent"}
n.style.backgroundColor="#be9667"}
document.getElementsByClassName("dot")[0].click();const closeCreation=()=>{document.body.style.overflowY="scroll";let overlay=document.getElementById("cart-item");let details=document.getElementById("cart-item-details");let cart=document.getElementById("addToCartBtn");overlay.style.opacity=0;overlay.style.zIndex=-12;details.removeChild(details.querySelector("img"));details.removeChild(cart)};const createCreation=(n,itemType,itemName)=>{document.body.style.overflowY="hidden";if(getCookie(itemName+itemType+"q")===null){let overlay=document.getElementById("cart-item");let details=document.getElementById("cart-item-details");let cart=document.createElement("div");let itemImg=document.createElement("img");itemImg.src=n.src;itemImg.classList.add("img");cart.classList.add("btn");cart.classList.add("add_to_cart-btn");cart.setAttribute("id","addToCartBtn");cart.innerHTML=`<span class="material-symbols-rounded">add_shopping_cart</span>&nbsp;&nbsp;Add to Cart`;details.appendChild(itemImg);cart.addEventListener("click",()=>{let cartBtn=document.getElementById("addToCartBtn");setCookie(itemName+itemType,itemType,1);setCookie(itemName+itemType+"q",getCookie(itemName+itemType+"q")!=null?parseInt(getCookie(itemName+itemType+"q"))+1:1,1);cartBtn.innerHTML=`<span class="material-symbols-rounded">add_shopping_cart</span>&nbsp;&nbsp;Add More ( ${getCookie(
        itemName + itemType + "q"
      )} )`});details.appendChild(cart);overlay.style.zIndex=12;overlay.style.opacity=1}else{let overlay=document.getElementById("cart-item");let details=document.getElementById("cart-item-details");let cart=document.createElement("div");let itemImg=document.createElement("img");itemImg.src=n.src;itemImg.classList.add("img");cart.classList.add("btn");cart.classList.add("add_to_cart-btn");cart.setAttribute("id","addToCartBtn");cart.innerHTML=`<span class="material-symbols-rounded">add_shopping_cart</span>&nbsp;&nbsp;Add More ( ${getCookie(
      itemName + itemType + "q"
    )} )`;details.appendChild(itemImg);cart.addEventListener("click",()=>{let cartBtn=document.getElementById("addToCartBtn");setCookie(itemName+itemType,itemType,1);setCookie(itemName+itemType+"q",getCookie(itemName+itemType+"q")!=null?parseInt(getCookie(itemName+itemType+"q"))+1:1,1);cartBtn.innerHTML=`<span class="material-symbols-rounded">add_shopping_cart</span>&nbsp;&nbsp;Add More ( ${getCookie(
        itemName + itemType + "q"
      )} )`});details.appendChild(cart);overlay.style.zIndex=12;overlay.style.opacity=1}};const changeToCloseCursor=(n)=>{let cursor=document.getElementById("cursor");let cursork=0;if(n===0){cursor.style.display="block";document.addEventListener("mousemove",function(e){var x=e.clientX;var y=e.clientY;cursor.style.left=x+"px";cursor.style.top=y+"px";cursor.style.rotate=(cursork+=12)+"deg"})}else{cursor.style.display="none"}};function setCookie(name,value,days){document.getElementById("cartBtn").style.left="11px";let expires="";if(days){let date=new Date();date.setTime(date.getTime()+days*24*60*60*1000);expires="; expires="+date.toUTCString()}
document.cookie=name+"="+value+expires+"; path=/"}
function getCookie(name){let nameEQ=name+"=";let cookies=document.cookie.split(";");for(let i=0;i<cookies.length;i++){let cookie=cookies[i].trim();if(cookie.indexOf(nameEQ)==0){return cookie.substring(nameEQ.length,cookie.length)}}
return null}
function deleteCookie(name){document.cookie=name+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}
function cart(){let cookie=document.cookie,names=[],quantity=[];cookie=cookie.split(";");for(let k=0;k<cookie.length;k++){if(k%2==0){continue}
names.push(cookie[k])}
for(let k=0;k<cookie.length;k++){if(k%2!=0){continue}
quantity.push(cookie[k])}
names=names.toString();quantity=quantity.toString();names=names.split("=");quantity=quantity.split("=");names=names.toString();quantity=quantity.toString();names=names.split(",");quantity=quantity.split(",");let name=[],q=[];for(let k=0;k<cookie.length;k++){if(k%2==0){continue}
name.push(quantity[k]);q.push(names[k])}
let string="";for(let k=0;k<name.length;k++){string+=`Id:%20${name[k]}%0DQuantity:%20${q[k]}%0D`}
let cookies=document.cookie.split(";");for(let i=0;i<cookies.length;i++){let cookie=cookies[i];let eqPos=cookie.indexOf("=");let name=eqPos>-1?cookie.substr(0,eqPos):cookie;document.cookie=name+"=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;"}
window.open(`mailto:skillrextechnologies@gmail.com?subject=New Order&body=${string}`)}
let date=new Date();document.getElementById("date").innerText=date.getFullYear()